In [1]:
import numpy as np

In [2]:
list = [0,1,2,3,4,5,6,7,8]

In [4]:
array = np.array(list).reshape((3,3))

In [5]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
mean_flattened=np.mean(array)

In [11]:
mean_axis1=np.mean(array,axis=0)

In [12]:
mean_axis2=np.mean(array,axis=1)

In [13]:
mean_key = [mean_axis1,mean_axis2,mean_flattened]

In [15]:
mean_key

[array([3., 4., 5.]), array([1., 4., 7.]), 4.0]

In [16]:
np.var(array)

6.666666666666667

In [17]:
np.std(array)

2.581988897471611

In [24]:
list = [0 , 1, None]

In [28]:
mean_key = []
var_key = []
std_key = []
max_key = []
min_key = []
sum_key = []
for i in list:
    value = np.mean(array,axis=i)
    mean_key.append(value)
    
    value1 = np.var(array,axis=i)
    var_key.append(value1)
    
    value2 = np.std(array,axis=i)
    std_key.append(value2)
    
    value3 = np.max(array,axis=i)
    max_key.append(value3)
    
    value4 = np.min(array,axis=i)
    min_key.append(value4)
    
    value5 = np.sum(array,axis=i)
    sum_key.append(value5)

In [30]:
calculations = {'mean':mean_key,'variance':var_key,
                   'standard-deviation':std_key,'max':max_key,'min':min_key,
                   'sum':sum_key}

In [31]:
calculations

{'mean': [array([3., 4., 5.]), array([1., 4., 7.]), 4.0],
 'variance': [array([6., 6., 6.]),
  array([0.66666667, 0.66666667, 0.66666667]),
  6.666666666666667],
 'standard-deviation': [array([2.44948974, 2.44948974, 2.44948974]),
  array([0.81649658, 0.81649658, 0.81649658]),
  2.581988897471611],
 'max': [array([6, 7, 8]), array([2, 5, 8]), 8],
 'min': [array([0, 1, 2]), array([0, 3, 6]), 0],
 'sum': [array([ 9, 12, 15]), array([ 3, 12, 21]), 36]}